name: Bananum
favicon: null
layout_spectrum: 0.02073
typography_spectrum: 0.02634
title: Que hacemos en Bananum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ece630'
    - '#ffffff'
    - '#231f20'
    - '#5e5924'
    - '#c0ba2c'
  brandStrength: 0.5
  lightness: 0.8800996951758862
  saturation: 0.26333391503430903
  rhythmicContrast: 0.9183744178153574
purpose: []
