name: Bananum
favicon: null
layout_spectrum: 0.7182189838495106
typography_spectrum: 0.592808170709759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.45290750707499683
  lightness: 0.8800996951758862
  saturation: 0.26333391503430903
  rhythmicContrast: 0.9183744178153574
purpose: []
